
name: 'dbt_mcdm_challenge'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  dbt_mcdm_challenge:
    staging:
      materialized: view
      schema: staging
    unification:
      materialized: view
      schema: unification
    metrics:
      materialized: table
      schema: final_metrics
