version: 2

models:
  - name: mcdm_tables
    description: "Merging all information from ads sources in the unified form"

sources:
  - name: staging
    database: mcdm-analytics
    schema: staging
    tables:
      - name: stg_ads_bing_all_data
      - name: stg_ads_creative_facebook_all_data
      - name: stg_ads_tiktok_ads_all_data
      - name: stg_promoted_tweets_twitter_all_data